apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: base-deployment
  template:
    metadata:
      labels:
        deployment: hellodev
    spec:
      containers:
      - name: the-container
        image: monopole/hello-custom:1
        command: ["/hello",
                  "--port=8080",
                  "--enableRiskyFeature=$(ENABLE_RISKY)"]
        ports:
        - containerPort: 8080
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: altGreeting
        - name: DONT_ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: enableRisky