apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

#patches:
## targeted patching -- replacing on small part of the deployment yaml
  # - target:
  #     kind: Deployment
  #     name: base-deployment
  #   patch: |-
  #     - op: replace
  #       path: /spec/replicas
  #       value: 2

## strategic path matching - slighly larger 
  # - patch: |-
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     metadata:
  #       name: base-deployment
  #     spec:
  #       replicas: 5
# file patching - replace ALL base template with the overlay deployment.yaml 
patches: 
- path: ./deployment.yaml